"""empty message

Revision ID: 62eb8977c381
Revises: 
Create Date: 2019-04-18 10:22:47.125000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62eb8977c381'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelName', sa.String(length=100), nullable=True),
    sa.Column('modelLink', sa.String(length=500), nullable=True),
    sa.Column('modelStatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('project_en', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project'),
    sa.UniqueConstraint('project_en')
    )
    op.create_table('case_dubbo_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('case_sys', sa.String(length=100), nullable=True),
    sa.Column('serviceName', sa.String(length=100), nullable=True),
    sa.Column('methodName', sa.String(length=100), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_type', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project_api.project'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_http_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('case_api', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_host', sa.String(length=500), nullable=True),
    sa.Column('case_url', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('api_type', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project_api.project'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_http_api')
    op.drop_table('case_dubbo_api')
    op.drop_table('project_api')
    op.drop_table('model_set')
    # ### end Alembic commands ###
